sudo: false
language: node_js
node_js:
  - 10 # use nodejs v10 LTS
cache: npm
branches:
  only:
    - master # build master branch only
install:
  - npm install -g hexo
  - npm install
before_script:
  - mkdir themes/next
  # clone next theme
  - curl -s https://api.github.com/repos/theme-next/hexo-theme-next/releases/latest | grep tarball_url | cut -d '"' -f 4 | wget -i - -O- | tar -zx -C themes/next --strip-components=1
  # copy the custom next theme config file
  - no | mv themes/next/* -i themes/hexo-theme-next/
script:
  - hexo clean
  - hexo generate # generate static files
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GH_TOKEN
  keep-history: true
  on:
    branch: master
  local-dir: public

# https://ehye.github.io/2020/03/28/deploy-hexo-to-gh-pages-by-travis/
